### PR TITLE
Mavenize pyRadiomics_GUI

### PR DESCRIPTION
**Pull request by imagejan**
This PR creates a Maven project for this plugin.

This allows to build using `mvn` from the command line, and it enables proper dependency management to ensure future compatibility with other third-party libraries shipped with Fiji/ImageJ (by inheriting managed versions from `pom-scijava`).

To use this maven project in an IDE (such as Eclipse), use *File > Import > Existing Maven Projects*.

### CODE REVIEW

**Comment by salimkanoun** [comment]
Thanks ImageJan,
Never done this before thanks for teaching me.

**Comment by salimkanoun** [comment]
Hi @imagejan ,

Now with the maven structure I have a problem to access the logo Icon in ImageJ Jar.

When I run in Eclipse the this.setIconImage(ImageIO.read(getClass().getResource("logo/logo_pyRadiomics.png"))) is OK

But when I run in ImageJ it don't find the correct file because it is in /resources/ subfolder in the jar.

How to solve this ?

Best regards,

Salim

**Comment by imagejan** [comment]
Judging from some other examples in the source code and on the forum, I'd suggest that specifying the absolute path with `/resources/` should work.

```java
getClass().getResource("/resources/logo/logo_pyRadiomics.png"))
```

**Comment by salimkanoun** [comment]
Thanks but if I use absolute path then the standalone (without ImageJ) run does not work.
So I moved the logo into the java folder and it is fine now.

I also updated my source code solving some problems and removing my index array of results (now generated on the fly when I get the results from the terminal).

**Pull request merged**
